name: dmc_threads_generator
description: dmc_threads_generator
version: 0.1.0
homepage: https://github.com/jWinterDay/dmc_threads
repository: https://github.com/jWinterDay/dmc_threads
issue_tracker: https://github.com/jWinterDay/dmc_threads/issues

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  dmc_threads_annotation: ^0.1.0

  source_gen: ^1.0.0
  code_builder: ^4.0.0
  build: ^2.0.3
  
dev_dependencies:
  build_runner: ^2.0.4
  pedantic: ^1.11.1