name: dmc_threads
description: dmc_threads
version: 0.0.1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  built_value: ^8.0.6
  built_collection: ^5.1.0
  collection: ^1.15.0
  dmc_threads_annotation: ^0.0.1
  
dev_dependencies:
  pedantic: ^1.11.1
  build_runner: ^1.12.2
  built_value_generator: ^8.0.6
  dmc_threads_generator: ^0.0.1
  test: ^1.17.9