name: dmc_threads
description: dmc_threads
version: 0.1.1
homepage: https://github.com/jWinterDay/dmc_threads
repository: https://github.com/jWinterDay/dmc_threads
issue_tracker: https://github.com/jWinterDay/dmc_threads/issues

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  collection: ^1.15.0
  dmc_threads_annotation: ^0.1.0
  freezed_annotation: ^0.14.2
  
dev_dependencies:
  json_serializable: ^4.1.3
  freezed: ^0.14.2
  pedantic: ^1.11.1
  build_runner: ^2.0.5
  test: ^1.17.9
  dmc_threads_generator: ^0.1.0