name: dmc_threads_annotation
description: dmc_threads_annotation
version: 0.1.0
homepage: https://github.com/jWinterDay/dmc_threads
repository: https://github.com/jWinterDay/dmc_threads
issue_tracker: https://github.com/jWinterDay/dmc_threads/issues

environment:
  sdk: ">=2.12.0 <3.0.0"

dev_dependencies:
  pedantic: ^1.11.1